apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-time-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: date-time-app
  template:
    metadata:
      labels:
        app: date-time-app
    spec:
      containers:
      - name: date-time-app
        image: justacoder03/date-time-app:latest
        ports:
        - containerPort: 8080