apiVersion: v1
kind: Service
metadata:
  name: date-time-service
  namespace: default
spec:
  selector:
    app: date-time-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP